import { StyleSheet } from 'react-native';
import { fontFamily } from '../../../theme/fonts';

const createStyles = ({ colors, spacing, borderRadius, shadows, isDark }) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: spacing[4],
      paddingTop: spacing[4],
      paddingBottom: spacing[8],
    },
    imageSection: {
      height: 180,
      marginBottom: 44,
      position: 'relative',
      width: '100%',
    },
    coverContainer: {
      borderRadius: 16,
      height: 180,
      overflow: 'hidden',
      position: 'relative',
      width: '100%',
    },
    coverImage: {
      height: '100%',
      width: '100%',
    },
    coverPlaceholder: {
      alignItems: 'center',
      height: '100%',
      justifyContent: 'center',
      width: '100%',
    },
    coverCameraBtn: {
      alignItems: 'center',
      borderRadius: 18,
      bottom: 12,
      elevation: 3,
      height: 36,
      justifyContent: 'center',
      position: 'absolute',
      right: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 3,
      width: 36,
    },
    avatarContainer: {
      borderRadius: 16,
      borderWidth: 3,
      bottom: -28,
      elevation: 4,
      height: 80,
      left: 16,
      overflow: 'visible',
      position: 'absolute',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 3,
      width: 80,
    },
    avatarImage: {
      borderRadius: 13,
      height: '100%',
      width: '100%',
    },
    avatarPlaceholder: {
      borderRadius: 13,
      height: '100%',
      width: '100%',
    },
    avatarCameraBtn: {
      alignItems: 'center',
      borderRadius: 14,
      borderWidth: 1.5,
      bottom: -6,
      elevation: 2,
      height: 28,
      justifyContent: 'center',
      position: 'absolute',
      right: -6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      width: 28,
    },
    fieldContainer: {
      marginBottom: 24,
      width: '100%',
    },
    fieldLabel: {
      fontSize: 14,
      fontFamily: fontFamily.regular,
    },
    flatInput: {
      borderBottomWidth: 1,
      fontFamily: fontFamily.medium,
      fontSize: 16,
      fontWeight: '600',
      paddingHorizontal: 0,
      paddingVertical: 8,
    },
    errorText: {
      fontSize: 12,
      fontFamily: fontFamily.regular,
      marginTop: 4,
    },
    dropdownContainer: {
      alignItems: 'center',
      borderWidth: 1,
      flexDirection: 'row',
      height: 52,
      justifyContent: 'space-between',
      paddingHorizontal: 16,
    },
    dropdownValue: {
      fontFamily: fontFamily.medium,
      fontSize: 15,
    },
    adminLabel: {
      fontFamily: fontFamily.regular,
      fontSize: 14,
      marginBottom: spacing[2],
    },
    adminList: {
      marginBottom: 24,
    },
    adminCardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: spacing[3],
      height: 72,
    },
    adminAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
    },
    adminInfo: {
      flex: 1,
      marginLeft: spacing[3],
    },
    adminName: {
      fontFamily: fontFamily.medium,
      fontSize: 15,
      fontWeight: '600',
    },
    adminRole: {
      fontFamily: fontFamily.regular,
      fontSize: 12,
      marginTop: 2,
    },
    adminMenuBtn: {
      padding: spacing[1],
    },
    adminPopupMenu: {
      position: 'absolute',
      right: 16,
      width: 220,
      alignSelf: undefined,
      elevation: 8,
      shadowOpacity: 0.15,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      paddingHorizontal: 0,
      zIndex: 999,
    },
    menuRow: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 48,
      paddingHorizontal: 16,
    },
    menuRowText: {
      fontFamily: fontFamily.medium,
      fontSize: 14,
      lineHeight: 20,
    },
    menuDivider: {
      height: 1,
      marginHorizontal: 16,
      marginVertical: 6,
    },
    buttonWrapper: {
      marginTop: 16,
      width: '100%',
    },
    submitButton: {
      alignItems: 'center',
      height: 52,
      justifyContent: 'center',
      width: '100%',
    },
    submitButtonText: {
      fontFamily: fontFamily.bold,
      fontSize: 16,
      fontWeight: '700',
    },
    cancelButton: {
      alignItems: 'center',
      marginTop: spacing[3],
      paddingVertical: spacing[2],
      width: '100%',
    },
    cancelButtonText: {
      fontFamily: fontFamily.bold,
      fontSize: 16,
      fontWeight: '700',
    },
  });

export default createStyles;
