export const AI_BUDDIES = [
  {
    id: 'buddy_1',
    name: 'Melissa',
    role: 'The Loyal Companion',
    description: 'Melissa provides consistent support. Her reassurance is always there when needed.',
    about: 'Melissa is a reliable source of support. Her comforting presence is always available whenever you need it.',
    image: 'https://randomuser.me/api/portraits/women/44.jpg',
    specialties: [
      'Weight Loss',
      'Daily Motivation',
      'Exercise Plans',
    ],
  },
  {
    id: 'buddy_2',
    name: 'Alex',
    role: 'The Expert Advisor',
    description: 'Alex is a sharp, strategic advisor for smart moves.',
    about: 'Alex offers well-researched advice and guides you to make smart, strategic choices.',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
    specialties: [
      'Nutrition',
      'Healthy Meals',
      'Calorie Tracking',
    ],
  },
  {
    id: 'buddy_3',
    name: 'Daniel',
    role: 'The Loyal Companion',
    description: 'Daniel is a dependable companion who supports you through challenges, always ready to help or share a laugh.',
    about: 'Daniel is a dependable companion who supports you through challenges, always ready to help or share a laugh.',
    image: 'https://randomuser.me/api/portraits/men/51.jpg',
    specialties: [
      'Mindfulness',
      'Stress Management',
      'Healthy Habits',
    ],
  },
  {
    id: 'buddy_4',
    name: 'Keith',
    role: 'The Expert Advisor',
    description: 'Keith is a calm advisor who helps users make sound decisions with insightful analysis and tailored recommendations.',
    about: 'Keith is a calm advisor who helps users make sound decisions with insightful analysis and tailored recommendations.',
    image: 'https://randomuser.me/api/portraits/men/45.jpg',
    specialties: [
      'Goal Tracking',
      'Motivation',
      'Progress Reviews',
    ],
  },
  {
    id: 'buddy_5',
    name: 'Aria',
    role: 'The Guiding Coach',
    description: 'Aria is a vibrant coach who empowers individuals to unlock their potential and embrace their strengths on a journey of self-discovery.',
    about: 'Aria is a vibrant coach who empowers individuals to unlock their potential and embrace their strengths on a journey of self-discovery.',
    image: 'https://randomuser.me/api/portraits/women/68.jpg',
    specialties: [
      'Weight Management',
      'Meal Planning',
      'Progress Tracking',
    ],
  },
  {
    id: 'buddy_6',
    name: 'Naomi',
    role: 'The Insightful Guide',
    description: 'Naomi offers guidance grounded in experience today',
    about: 'Naomi offers guidance grounded in experience today',
    image: 'https://randomuser.me/api/portraits/women/25.jpg',
    specialties: [
      'Mindfulness',
      'Stress Management',
      'Healthy Habits',
    ],
  },
  {
    id: 'buddy_7',
    name: 'Natalie',
    role: 'The Guiding Coach',
    description: 'Natalie motivates action with clear, supportive guidance.',
    about: 'Natalie motivates action with clear, supportive guidance.',
    image: 'https://randomuser.me/api/portraits/women/69.jpg',
    specialties: [
      'Goal Tracking',
      'Motivation',
      'Progress Reviews',
    ],
  },
];

export const MOCK_BUDDY_FEED = [
  {
    id: 'post_1',
    userId: 'buddy_1',
    username: 'Melissa',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    image: require('../assets/images/survey_1.png'),
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: false,
  },
  {
    id: 'post_2',
    userId: 'buddy_2',
    username: 'Alex',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    currentWeight: '80kgs',
    timeAgo: '1d ago',
    text: 'Consistency is key. Keep pushing forward and never give up on your goals. Every small step counts towards a healthier you!',
    likes: 45,
    comments: 8,
    shares: 5,
    liked: true,
    saved: true,
  },
  {
    id: 'post_3',
    userId: 'buddy_1',
    username: 'Melissa',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    currentWeight: '66.5kgs',
    timeAgo: '2d ago',
    text: 'Remember to stay hydrated! Drinking enough water is crucial for weight loss and overall health.',
    likes: 24,
    comments: 5,
    shares: 2,
    liked: false,
    saved: false,
  },
  {
    id: 'post_4',
    userId: 'buddy_2',
    username: 'Alex',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    currentWeight: '81kgs',
    timeAgo: '3d ago',
    text: 'Had a great workout today. It is important to mix cardio and strength training for the best results.',
    likes: 89,
    comments: 12,
    shares: 20,
    liked: true,
    saved: false,
  },
  {
    id: 'post_5',
    userId: 'buddy_3',
    username: 'Daniel',
    avatar: 'https://randomuser.me/api/portraits/men/51.jpg',
    currentWeight: '75kgs',
    timeAgo: '4d ago',
    text: 'Meal prep Sunday! Planning your meals ahead of time makes it so much easier to stay on track during a busy week.',
    image: require('../assets/images/survey_2.png'),
    likes: 156,
    comments: 45,
    shares: 33,
    liked: false,
    saved: true,
  },
  {
    id: 'post_6',
    userId: 'buddy_4',
    username: 'Keith',
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    currentWeight: '90kgs',
    timeAgo: '1w ago',
    text: 'Sleep is just as important as diet and exercise. Aim for 7-9 hours of quality sleep each night to support your goals.',
    likes: 67,
    comments: 14,
    shares: 8,
    liked: false,
    saved: false,
  },
  {
    id: 'post_7',
    userId: 'buddy_5',
    username: 'Aria',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    currentWeight: '62kgs',
    timeAgo: '2w ago',
    text: 'Celebrate your non-scale victories! How your clothes fit, your energy levels, and your mood are all great indicators of progress.',
    likes: 210,
    comments: 56,
    shares: 42,
    liked: true,
    saved: true,
  }
];
