import { APP_IMAGES } from '../constants/images';

export const MOCK_POSTS = [
  {
    id: '1',
    username: 'Weight loss Ladies',
    currentWeight: '64kgs',
    timeAgo: '12h ago',
    text: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    image: require('../assets/images/find_robi.png'),
    likes: 12,
    comments: 32,
    shares: 15,
    saved: false,
    liked: false,
    avatar: APP_IMAGES.userAvatar,
    tab: 'trending',
  },
  {
    id: '2',
    username: 'Phillips in TN',
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    image: require('../assets/images/find_buddy.png'),
    likes: 24,
    comments: 8,
    shares: 5,
    saved: true,
    liked: false,
    avatar: APP_IMAGES.profileAvatar,
    tab: 'trending',
  },
  {
    id: '3',
    username: 'FitJourney22',
    currentWeight: '78kgs',
    timeAgo: '4h ago',
    text: 'Just completed my first 5K run! 🏃‍♂️ Small steps every day lead to big transformations. Keep pushing forward, your future self will thank you!',
    image: require('../assets/images/survey_dance.png'),
    likes: 47,
    comments: 19,
    shares: 11,
    saved: false,
    liked: false,
    avatar: APP_IMAGES.userAvatar,
    tab: 'wlb',
  },
  {
    id: '4',
    username: 'HealthyHannah',
    currentWeight: '58kgs',
    timeAgo: '1d ago',
    text: 'Meal prep Sunday done right! 🥗 Prepared 5 days worth of balanced meals. Planning ahead makes staying on track so much easier.',
    image: null,
    likes: 63,
    comments: 14,
    shares: 22,
    saved: false,
    liked: false,
    avatar: APP_IMAGES.profileAvatar,
    tab: 'wlb',
  },
];

/**
 * My Groups — list of groups the current user belongs to.
 * Shape mirrors the future GET /groups/my response.
 */
export const MOCK_MY_GROUPS = [
  {
    id: 'g1',
    groupName: 'Daily Walkers Club',
    groupImage: APP_IMAGES.findRobi,
    groupCoverImage: APP_IMAGES.survey1,
    totalMembers: 1245,
    status: 'join_now',
  },
  {
    id: 'g2',
    groupName: 'Small Steps Circle',
    groupImage: APP_IMAGES.findBuddy,
    groupCoverImage: APP_IMAGES.survey2,
    totalMembers: 892,
    status: 'join_now',
  },
  {
    id: 'g3',
    groupName: 'Healthy Habits Crew',
    groupImage: APP_IMAGES.surveyDance,
    groupCoverImage: APP_IMAGES.survey3,
    totalMembers: 2130,
    status: 'pending',
  },
  {
    id: 'g4',
    groupName: 'Morning Motivation Group',
    groupImage: APP_IMAGES.survey1,
    groupCoverImage: APP_IMAGES.survey4,
    totalMembers: 764,
    status: 'join_now',
  },
  {
    id: 'g5',
    groupName: 'Lose Together Community',
    groupImage: APP_IMAGES.survey2,
    groupCoverImage: APP_IMAGES.survey5,
    totalMembers: 3420,
    status: 'join_now',
  },
  {
    id: 'g6',
    groupName: 'Yoga & Wellness',
    groupImage: APP_IMAGES.survey3,
    groupCoverImage: APP_IMAGES.survey6,
    totalMembers: 980,
    status: 'joined',
  },
];

/**
 * Group Posts — posts made inside groups.
 * Shape mirrors the future GET /groups/:id/posts response.
 * Each post carries both group info and author info.
 */
export const MOCK_GROUP_POSTS = [
  {
    id: 'gp1',
    groupId: 'g1',
    groupName: 'Daily Walkers Club',
    groupImage: APP_IMAGES.findRobi,
    userId: 'u1',
    userName: 'Savannah Nguyen',
    userProfileImage: APP_IMAGES.userAvatar,
    postDescription:
      'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    postImage: require('../assets/images/find_robi.png'),
    createdAt: '12h ago',
    likeCount: 12,
    commentCount: 32,
    shareCount: 15,
    liked: false,
    saved: false,
  },
  {
    id: 'gp2',
    groupId: 'g2',
    groupName: 'Small Steps Circle',
    groupImage: APP_IMAGES.findBuddy,
    userId: 'u2',
    userName: 'Alexandra Smith',
    userProfileImage: APP_IMAGES.profileAvatar,
    postDescription:
      'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    postImage: require('../assets/images/find_buddy.png'),
    createdAt: '12h ago',
    likeCount: 24,
    commentCount: 8,
    shareCount: 5,
    liked: false,
    saved: true,
  },
  {
    id: 'gp3',
    groupId: 'g1',
    groupName: 'Daily Walkers Club',
    groupImage: APP_IMAGES.findRobi,
    userId: 'u3',
    userName: 'Emily Rodriguez',
    userProfileImage: APP_IMAGES.userAvatar,
    postDescription:
      'Just completed my first 5K run! 🏃‍♂️ Small steps every day lead to big transformations. Keep pushing forward, your future self will thank you!',
    postImage: require('../assets/images/survey_dance.png'),
    createdAt: '4h ago',
    likeCount: 47,
    commentCount: 19,
    shareCount: 11,
    liked: false,
    saved: false,
  },
  {
    id: 'gp4',
    groupId: 'g3',
    groupName: 'Healthy Habits Crew',
    groupImage: APP_IMAGES.surveyDance,
    userId: 'u4',
    userName: 'Hannah Miller',
    userProfileImage: APP_IMAGES.profileAvatar,
    postDescription:
      'Meal prep Sunday done right! 🥗 Prepared 5 days worth of balanced meals. Planning ahead makes staying on track so much easier.',
    postImage: null,
    createdAt: '1d ago',
    likeCount: 63,
    commentCount: 14,
    shareCount: 22,
    liked: false,
    saved: false,
  },
  {
    id: 'gp5',
    groupId: 'g4',
    groupName: 'Morning Motivation Group',
    groupImage: APP_IMAGES.survey1,
    userId: 'u5',
    userName: 'Jessica Turner',
    userProfileImage: APP_IMAGES.userAvatar,
    postDescription:
      'Early morning run completed! Nothing beats the feeling of fresh air and endorphins to start the day. Who else is a morning runner? 🌅',
    postImage: require('../assets/images/find_robi.png'),
    createdAt: '6h ago',
    likeCount: 35,
    commentCount: 21,
    shareCount: 8,
    liked: false,
    saved: false,
  },
  {
    id: 'gp6',
    groupId: 'g5',
    groupName: 'Lose Together Community',
    groupImage: APP_IMAGES.survey2,
    userId: 'u6',
    userName: 'Michael Chen',
    userProfileImage: APP_IMAGES.profileAvatar,
    postDescription:
      'Week 3 on keto and already seeing amazing results! Down 8 lbs and feeling more energetic than ever. The cravings are finally subsiding.',
    postImage: require('../assets/images/find_buddy.png'),
    createdAt: '2h ago',
    likeCount: 89,
    commentCount: 42,
    shareCount: 18,
    liked: false,
    saved: false,
  },
  {
    id: 'gp7',
    groupId: 'g6',
    groupName: 'Yoga & Wellness',
    groupImage: APP_IMAGES.survey3,
    userId: 'u7',
    userName: 'Sarah Johnson',
    userProfileImage: APP_IMAGES.userAvatar,
    postDescription:
      'Today\'s yoga flow was exactly what I needed. Remember: flexibility isn\'t just about the body, it\'s about the mind too. 🧘‍♀️ Namaste!',
    postImage: null,
    createdAt: '8h ago',
    likeCount: 56,
    commentCount: 27,
    shareCount: 13,
    liked: false,
    saved: false,
  },
  {
    id: 'gp8',
    groupId: 'g2',
    groupName: 'Small Steps Circle',
    groupImage: APP_IMAGES.findBuddy,
    userId: 'u8',
    userName: 'David Phillips',
    userProfileImage: APP_IMAGES.profileAvatar,
    postDescription:
      'Beautiful day for a hike in the Smoky Mountains! Nature is the best therapy. Getting those steps in while enjoying the views. 🏔️',
    postImage: require('../assets/images/survey_dance.png'),
    createdAt: '3h ago',
    likeCount: 41,
    commentCount: 15,
    shareCount: 9,
    liked: false,
    saved: false,
  },
];

export const MOCK_PENDING_APPROVAL_REQUESTS = [
  {
    id: 'req1',
    name: 'Michael Chen',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    mutualMembers: 4,
    invitedBy: null,
    isOnline: true,
  },
  {
    id: 'req2',
    name: 'Sarah Jenkins',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    mutualMembers: 2,
    invitedBy: null,
    isOnline: false,
  },
  {
    id: 'req3',
    name: 'David Miller',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    mutualMembers: 0,
    invitedBy: 'Olivia K.',
    isOnline: false,
  },
];

export const MOCK_PENDING_APPROVAL_POSTS = [
  {
    id: 'pap1',
    user: {
      name: 'MGIGD17',
    },
    username: 'MGIGD17',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
    isOnline: true,
    createdAt: '12h ago',
    timeAgo: '12h ago',
    description: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    text: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    images: [require('../assets/images/find_robi.png')],
    image: require('../assets/images/find_robi.png'),
    status: 'pending',
    currentWeight: '67kgs',
  },
];


