import { APP_IMAGES } from '../images';

// ─── Blocked Users ───────────────────────────────────────────────────────────

export const blockedUsersData = [
  { id: '1', name: 'Sarah M.',   blockedDate: 'Jun 4, 2026', avatar: APP_IMAGES.userAvatar },
  { id: '2', name: 'James L.',   blockedDate: 'Jun 4, 2026', avatar: APP_IMAGES.userAvatar },
  { id: '3', name: 'Emily R.',   blockedDate: 'Jun 4, 2026', avatar: APP_IMAGES.userAvatar },
  { id: '4', name: 'Michael T.', blockedDate: 'Jun 4, 2026', avatar: APP_IMAGES.userAvatar },
  { id: '5', name: 'Olivia K.',  blockedDate: 'Jun 4, 2026', avatar: APP_IMAGES.userAvatar },
];

// ─── Awards ──────────────────────────────────────────────────────────────────

export const awardLevels = [
  { id: 'starter',    labelKey: 'awards.levels.starter',    pointsKey: 'awards.levels.starterPts',    imgUrl: APP_IMAGES.starter },
  { id: 'risingStar', labelKey: 'awards.levels.risingStar', pointsKey: 'awards.levels.risingStarPts', imgUrl: APP_IMAGES.risingStar },
  { id: 'supporter',  labelKey: 'awards.levels.supporter',  pointsKey: 'awards.levels.supporterPts',  imgUrl: APP_IMAGES.supporter },
  { id: 'energizer',  labelKey: 'awards.levels.energizer',  pointsKey: 'awards.levels.energizerPts',  imgUrl: APP_IMAGES.energizerLight },
  { id: 'achiever',   labelKey: 'awards.levels.achiever',   pointsKey: 'awards.levels.achieverPts',   imgUrl: APP_IMAGES.achiever },
  { id: 'champion',   labelKey: 'awards.levels.champion',   pointsKey: 'awards.levels.championPts',   imgUrl: APP_IMAGES.champion },
  { id: 'legend',     labelKey: 'awards.levels.legend',     pointsKey: 'awards.levels.legendPts',     imgUrl: APP_IMAGES.legend },
  { id: 'elite',      labelKey: 'awards.levels.elite',      pointsKey: 'awards.levels.elitePts',      imgUrl: APP_IMAGES.elite },
];

export const awardLevelRanges = [
  { id: 'starter',    min: 0,     max: 99,       labelKey: 'awards.levels.starter' },
  { id: 'risingStar', min: 100,   max: 199,      labelKey: 'awards.levels.risingStar' },
  { id: 'supporter',  min: 200,   max: 399,      labelKey: 'awards.levels.supporter' },
  { id: 'energizer',  min: 400,   max: 699,      labelKey: 'awards.levels.energizer' },
  { id: 'achiever',   min: 700,   max: 999,      labelKey: 'awards.levels.achiever' },
  { id: 'champion',   min: 1000,  max: 9999,     labelKey: 'awards.levels.champion' },
  { id: 'legend',     min: 10000, max: 19999,    labelKey: 'awards.levels.legend' },
  { id: 'elite',      min: 20000, max: Infinity, labelKey: 'awards.levels.elite' },
];

export const earnPoints = [
  { id: 'post',      labelKey: 'awards.earn.post',      pointsKey: 'awards.earn.postPts',      imageUrl: APP_IMAGES.post },
  { id: 'comment',   labelKey: 'awards.earn.comment',   pointsKey: 'awards.earn.commentPts',   imageUrl: APP_IMAGES.comment },
  { id: 'liked',     labelKey: 'awards.earn.liked',     pointsKey: 'awards.earn.likedPts',     imageUrl: APP_IMAGES.postLike },
  { id: 'shared',    labelKey: 'awards.earn.shared',    pointsKey: 'awards.earn.sharedPts',    imageUrl: APP_IMAGES.sharePost },
  { id: 'sharePost', labelKey: 'awards.earn.sharePost', pointsKey: 'awards.earn.sharePostPts', imageUrl: APP_IMAGES.sharePost },
];

// ─── Leaderboard ─────────────────────────────────────────────────────────────

export const leaderboardFilterOptions = [
  { id: 'allTime', labelKey: 'leaderboard.allTime' },
  { id: 'week',    labelKey: 'leaderboard.thisWeek' },
  { id: 'month',   labelKey: 'leaderboard.thisMonth' },
];

export const leaderboardData = {
  week: [
    { id: '1', rank: 1, name: 'Emma Carter',     points: 28400, avatar: APP_IMAGES.userAvatar },
    { id: '2', rank: 2, name: 'Liam Reynolds',   points: 18000, avatar: APP_IMAGES.userAvatar },
    { id: '3', rank: 3, name: 'Olivia Martinez', points: 5400,  avatar: APP_IMAGES.userAvatar },
    { id: '4', rank: 4, name: 'Noah Thompson',   points: 800,   avatar: APP_IMAGES.userAvatar },
    { id: '5', rank: 5, name: 'Ava Wilson',       points: 650,   avatar: APP_IMAGES.userAvatar },
    { id: '6', rank: 6, name: 'Benjamin Davis',  points: 250,   avatar: APP_IMAGES.userAvatar },
    { id: '7', rank: 7, name: 'Albert Flores',   points: 150,   avatar: APP_IMAGES.userAvatar },
    { id: '8', rank: 8, name: 'Ralph Edwards',   points: 50,    avatar: APP_IMAGES.userAvatar },
  ],
  month: [
    { id: '1', rank: 1, name: 'Noah Thompson',   points: 23499, avatar: APP_IMAGES.userAvatar },
    { id: '2', rank: 2, name: 'Liam Reynolds',   points: 17500, avatar: APP_IMAGES.userAvatar },
    { id: '3', rank: 3, name: 'Benjamin Davis',  points: 5200,  avatar: APP_IMAGES.userAvatar },
    { id: '4', rank: 4, name: 'Ava Wilson',       points: 799,   avatar: APP_IMAGES.userAvatar },
    { id: '5', rank: 5, name: 'Albert Flores',   points: 656,   avatar: APP_IMAGES.userAvatar },
    { id: '6', rank: 6, name: 'Olivia Martinez', points: 269,   avatar: APP_IMAGES.userAvatar },
    { id: '7', rank: 7, name: 'Emma Carter',     points: 130,   avatar: APP_IMAGES.userAvatar },
    { id: '8', rank: 8, name: 'Ralph Edwards',   points: 20,    avatar: APP_IMAGES.userAvatar },
  ],
  allTime: [
    { id: '1', rank: 1, name: 'Noah Thompson',   points: 25560, avatar: APP_IMAGES.userAvatar },
    { id: '2', rank: 2, name: 'Emma Carter',     points: 16720, avatar: APP_IMAGES.userAvatar },
    { id: '3', rank: 3, name: 'Liam Reynolds',   points: 5600,  avatar: APP_IMAGES.userAvatar },
    { id: '4', rank: 4, name: 'Ava Wilson',       points: 769,   avatar: APP_IMAGES.userAvatar },
    { id: '5', rank: 5, name: 'Olivia Martinez', points: 648,   avatar: APP_IMAGES.userAvatar },
    { id: '6', rank: 6, name: 'Albert Flores',   points: 278,   avatar: APP_IMAGES.userAvatar },
    { id: '7', rank: 7, name: 'Benjamin Davis',  points: 120,   avatar: APP_IMAGES.userAvatar },
    { id: '8', rank: 8, name: 'Ralph Edwards',   points: 30,    avatar: APP_IMAGES.userAvatar },
  ],
};

export const yourRankData = {
  week:    { rank: 12, points: 580 },
  month:   { rank: 8,  points: 25000 },
  allTime: { rank: 24, points: 542 },
};

// ─── Saved Posts ─────────────────────────────────────────────────────────────

export const savedPostsMockData = [
  // ── Text — plain ───────────────────────────────────────────────────────────
  {
    id: 'sp-1',
    type: 'text',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: "Focused on mindful eating this week. It's not just about the calories, it's about how the food makes you feel. Fueling my body with intention. 🥑✨ #HealthyMindset",
    feeling: null,
    image: null,
    video: null,
    videoDuration: null,
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: true,
  },
  // ── Text — with feeling (×3 to match Figma list) ──────────────────────────
  {
    id: 'sp-2',
    type: 'text',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: 'Feeling accomplished after hitting my water goal for 7 days straight! Small wins lead to big changes.',
    feeling: '😊 happy',
    image: null,
    video: null,
    videoDuration: null,
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: true,
  },
  {
    id: 'sp-3',
    type: 'text',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: 'Feeling accomplished after hitting my water goal for 7 days straight! Small wins lead to big changes.',
    feeling: '😊 happy',
    image: null,
    video: null,
    videoDuration: null,
    likes: 12,
    comments: 32,
    shares: 15,
    liked: true,
    saved: true,
  },
  {
    id: 'sp-4',
    type: 'text',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: 'Feeling accomplished after hitting my water goal for 7 days straight! Small wins lead to big changes.',
    feeling: '😊 happy',
    image: null,
    video: null,
    videoDuration: null,
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: true,
  },
  // ── Photo posts ────────────────────────────────────────────────────────────
  {
    id: 'sp-5',
    type: 'photo',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    feeling: null,
    image: APP_IMAGES.survey1,
    video: null,
    videoDuration: null,
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: true,
  },
  {
    id: 'sp-6',
    type: 'photo',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    feeling: null,
    image: APP_IMAGES.survey1,
    video: null,
    videoDuration: null,
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: true,
  },
  // ── Video posts — image used as thumbnail; swap video for a real uri later ─
  {
    id: 'sp-7',
    type: 'video',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: "Check out my 5-minute morning core blast! No equipment needed, just you and the mat. Let's start the day strong! 💪",
    feeling: null,
    thumbnail: APP_IMAGES.wlbLogo,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    videoDuration: '2:34',
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: true,
  },
  {
    id: 'sp-8',
    type: 'video',
    username: 'MGIGD17',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: '67kgs',
    timeAgo: '12h ago',
    text: "Check out my 5-minute morning core blast! No equipment needed, just you and the mat. Let's start the day strong! 💪",
    feeling: null,
    thumbnail: APP_IMAGES.wlbLogo,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    videoDuration: '2:34',
    likes: 12,
    comments: 32,
    shares: 15,
    liked: false,
    saved: true,
  },
  // ── Group post ─────────────────────────────────────────────────────────────
  {
    id: 'sp-9',
    type: 'group',
    username: 'Weight loss Ladies',
    avatar: APP_IMAGES.userAvatar,
    currentWeight: null,
    timeAgo: 'Savannah Nguyen · 12h ago',
    text: 'Shed those extra pounds and embrace a healthier, more vibrant you! Discover new ways to stay active, nourish your body, and boost your confidence along the journey to wellness!',
    feeling: null,
    image: APP_IMAGES.survey3,
    video: null,
    videoDuration: null,
    likes: 12,
    comments: 15,
    shares: 15,
    liked: false,
    saved: true,
  },
];

export const notificationMockData = [
  {
    id: 'n1',
    type: 'buddyRequest',
    title: 'New Buddy Request',
    message: 'Sarah M. wants to connect with you as a buddy.',
    time: '2m ago',
    section: 'Today',
    isRead: false,
    user: {
      name: 'Sarah M.',
      avatar: APP_IMAGES.userAvatar,
    },
  },
  {
    id: 'n2',
    type: 'like',
    title: 'Someone liked your post',
    message: 'Alexandra liked your progress update.',
    time: 'Yesterday · 8:42 PM',
    section: 'Today',
    isRead: true,
    user: {
      name: 'Alexandra',
      avatar: APP_IMAGES.userAvatar,
    },
  },
  {
    id: 'n3',
    type: 'groupJoinRequest',
    title: 'Group Join Request',
    message: 'Emma requested to join your GLP-1 Support Group.',
    time: 'Yesterday · 8:42 PM',
    section: 'Earlier',
    isRead: false,
    user: {
      name: 'Emma',
      avatar: APP_IMAGES.userAvatar,
    },
  },
  {
    id: 'n4',
    type: 'comment',
    title: 'New Comment',
    message: 'David commented on your post: "This is so inspiring! Keep it up!"',
    time: 'Yesterday · 8:42 PM',
    section: 'Earlier',
    isRead: false,
    user: {
      name: 'David',
      avatar: APP_IMAGES.userAvatar,
    },
  },
  {
    id: 'n5',
    type: 'buddyRequest',
    title: 'New Buddy Request',
    message: 'Sarah M. wants to connect with you as a buddy.',
    time: 'Yesterday · 8:42 PM',
    section: 'Earlier',
    isRead: true,
    user: {
      name: 'Sarah M.',
      avatar: APP_IMAGES.userAvatar,
    },
  },
  {
    id: 'n6',
    type: 'like',
    title: 'Someone liked your post',
    message: 'Alexandra liked your progress update.',
    time: 'Yesterday · 8:42 PM',
    section: 'Earlier',
    isRead: true,
    user: {
      name: 'Alexandra',
      avatar: APP_IMAGES.userAvatar,
    },
  },
  {
    id: 'n7',
    type: 'groupPost',
    title: 'New Group Post',
    message: 'Mona shared a new post in GLP-1 Support Group.',
    time: 'Yesterday · 8:42 PM',
    section: 'Earlier',
    isRead: true,
    user: {
      name: 'Mona',
      avatar: APP_IMAGES.userAvatar,
    },
  },
];
